export const FETCH_LIKE_REQUEST = 'FETCH_LIKE_REQUEST'
export const FETCH_LIKE_FAIL = 'FETCH_LIKE_FAIL'
export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS'

export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST'
export const CREATE_LIKE_FAIL = 'CREATE_LIKE_FAIL'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'


export const DELETE_LIKE_REQUEST = 'DELETE_LIKE_REQUEST'
export const DELETE_LIKE_FAIL = 'DELETE_LIKE_FAIL'
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS'