export const FETCH_POST_REQUEST  = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS  = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAIL  = 'FETCH_POST_FAIL'

export const FETCH_POSTBYUSER_REQUEST  = 'FETCH_POSTBYUSER_REQUEST'
export const FETCH_POSTBYUSER_SUCCESS  = 'FETCH_POSTBYUSER_SUCCESS'
export const FETCH_POSTBYUSER_FAIL  = 'FETCH_POSTBYUSER_FAIL'

export const CREATE_POST_REQUEST  = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS  = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL  = 'CREATE_POST_FAIL'

export const RELOAD_POST  = 'RELOAD_POST'
export const FETCH_POST_SCROLL  = 'FETCH_POST_SCROLL'